  const projects = [
    { name:"Vero", roles:"Customer & Provider apps", pc1:"#1c1612", pc2:"#2a2118",
      stat:"14.2K iOS · 1,000+ Android",
      desc:"Book a car wash or an AC wash — or gift the visit. Packages and wallet/Mada checkout; providers run a stepper with before/after photos.",
      tags:["Wallet / Mada","Gift flow","Job stepper","Maps"],
      links:[
        { group:"Customer", label:"App Store",   url:"https://apps.apple.com/us/app/%D9%81%D9%8A%D8%B1%D9%88-vero/id6737767544" },
        { group:"Customer", label:"Google Play", url:"https://play.google.com/store/apps/details?id=com.wady.vero" },
        { group:"Provider", label:"Google Play", url:"https://play.google.com/store/apps/details?id=com.wady.veroprovider" },
      ],
      shots:[
        { src:"assets/vero-2-home.png",           label:"Home & services" },
        { src:"assets/vero-3-packages.png",       label:"Wash packages" },
        { src:"assets/vero-6-package-detail.png", label:"Package detail & payment" },
        { src:"assets/vero-4-cars.png",           label:"My vehicles" },
        { src:"assets/vero-5-coupons.png",        label:"Coupons & offers" },
        { src:"assets/vero-1-splash.png",         label:"Splash & branding" },
      ],
      glyph:'<path d="M4 15c0-5 3.5-9 8-9s8 4 8 9" stroke="white" stroke-width="1.6" fill="none" stroke-linecap="round"/><circle cx="8" cy="17" r="1.5" fill="white"/><circle cx="16" cy="17" r="1.5" fill="white"/>' },
    { name:"GTech", roles:"Customer & Merchant apps", pc1:"#1a1a1a", pc2:"#262626",
      stat:"Quote-to-order marketplace",
      desc:"Owners request parts by photo and spec. Merchants bid per item — availability, VAT, delivery — then fulfill pickup or courier, with in-app chat on Pusher. Marketing deep links open an order or a store, depending on the campaign.",
      tags:["Photo RFQ","Per-item bids","Pusher","Deep links"],
      links:[
        { group:"Customer", label:"App Store",   url:"https://apps.apple.com/us/app/gtech-%D8%BA%D9%8A%D8%A7%D8%B1%D8%AA%D9%83/id6761782045" },
        { group:"Customer", label:"Google Play", url:"https://play.google.com/store/apps/details?id=com.wady.ghiartech" },
        { group:"Merchant", label:"App Store",   url:"https://apps.apple.com/us/app/%D8%BA%D9%8A%D8%A7%D8%B1%D8%AA%D9%83-%D8%A3%D8%B9%D9%85%D8%A7%D9%84/id6762350414" },
        { group:"Merchant", label:"Google Play", url:"https://play.google.com/store/apps/details?id=com.wady.gtechseller" },
      ],
      shots:[
        { src:"assets/gtech-1-home.png",    label:"Home & merchants" },
        { src:"assets/gtech-2-orders.png",  label:"My orders" },
        { src:"assets/gtech-3-store.png",   label:"Store profile" },
        { src:"assets/gtech-4-quotes.png",  label:"Quote requests" },
        { src:"assets/gtech-5-splash.png",  label:"Splash & branding" },
      ],
      glyph:'<path d="M14.7 6.3a3.5 3.5 0 00-4.9 4.2L4 16.3 5.7 18l5.8-5.8a3.5 3.5 0 004.2-4.9l-2 2-1.4-1.4 2-2z" fill="white"/>' },
    { name:"Invastro", roles:"Idea Owner & Investor apps", pc1:"#0a1a3d", pc2:"#0d2a6b",
      stat:"Owners × investors",
      desc:"List a project or find capital — filter by city, sector, and funding, then chat in-app on Pusher without sharing a phone number.",
      tags:["Capital matching","Pusher chat","City / sector filters","Private chat"],
      coverPos:"center 46%",
      links:[
        { label:"App Store",   url:"https://apps.apple.com/us/app/invastro/id6769418304" },
        { label:"Google Play", url:"https://play.google.com/store/apps/details?id=com.wady.invastro" },
      ],
      shots:[
        { src:"assets/invastro-2-browse.png", label:"Browse & filter opportunities" },
        { src:"assets/invastro-3-detail.png", label:"Opportunity detail & capital" },
        { src:"assets/invastro-6-chat.png",   label:"Direct chat with owners" },
        { src:"assets/invastro-4-create.png", label:"Create a listing" },
        { src:"assets/invastro-5-manage.png", label:"Manage listings & views" },
        { src:"assets/invastro-1-splash.png", label:"Splash & branding" },
      ],
      glyph:'<path d="M12 3l7 4v10l-7 4-7-4V7l7-4z" stroke="white" stroke-width="1.6" fill="none"/><path d="M12 8v8M8.5 10v4M15.5 10v4" stroke="white" stroke-width="1.6" stroke-linecap="round"/>' },
    { name:"Captainz", roles:"Customer & Rider apps", pc1:"#3d2412", pc2:"#5a3419",
      stat:"12K+ iOS · 10K+ Android · 5.0★ (164 reviews)",
      desc:"Book a wash at a saved pin or buy a package. Pay from wallet or Mada, add extras, and redeem partner vouchers — riders take jobs on the map and climb a points board. Share the app: when enough people install through your link and complete a first order, you get a gift. Deep links carry the invite.",
      tags:["Referrals","Deep links","Maps","Wallet"],
      links:[
        { group:"Customer", label:"App Store",   url:"https://apps.apple.com/us/app/%D9%83%D8%A7%D8%A8%D8%AA%D9%86%D8%B2-captainz/id6751917300" },
        { group:"Customer", label:"Google Play", url:"https://play.google.com/store/apps/details?id=com.captainz.captainz" },
        { group:"Rider",    label:"App Store",   url:"https://apps.apple.com/us/app/captainz-rider/id6751917266" },
        { group:"Rider",    label:"Google Play", url:"https://play.google.com/store/apps/details?id=com.captainz.captainzprovider" },
      ],
      shots:[
        { src:"assets/captains-1-splash.png",         label:"Splash & branding" },
        { src:"assets/captains-2-home.png",           label:"Home & services" },
        { src:"assets/captains-3-gift.png",           label:"Send a gift" },
        { src:"assets/captains-4-packages.png",       label:"Wash packages" },
        { src:"assets/captains-5-coupons.png",        label:"Discount codes" },
        { src:"assets/captains-6-cars.png",           label:"My vehicles" },
        { src:"assets/captains-7-package-detail.png", label:"Package detail & payment" },
        { src:"assets/captains-8-branding.png",       label:"Brand intro" },
        { src:"assets/captains-9-booking.png",        label:"Booking details" },
        { src:"assets/captains-10-leaderboard.png",   label:"Captain leaderboard" },
      ],
      glyph:'<path d="M12 3l2 6h6l-5 4 2 6-5-4-5 4 2-6-5-4h6z" fill="white"/>' },
    { name:"Soapy", roles:"Customer & Captain apps", pc1:"#1c1612", pc2:"#2a2118",
      stat:"5.32K iOS · 500+ Android",
      desc:"Book a wash or a named package with extras included. Pay by Tabby, Mada, or wallet — captains run jobs from a date-filtered earnings dashboard.",
      tags:["Tabby","Wallet","Packages","Earnings"],
      links:[
        { group:"Customer", label:"App Store",   url:"https://apps.apple.com/us/app/soapy-%D8%B3%D9%88%D8%A8%D9%8A/id6738302789" },
        { group:"Customer", label:"Google Play", url:"https://play.google.com/store/apps/details?id=sa.soapy.app" },
        { group:"Captain",  label:"Google Play", url:"https://play.google.com/store/apps/details?id=sa.soapy.driver" },
      ],
      shots:[
        { src:"assets/soapy-2-home.png",              label:"Home, wallet & packages" },
        { src:"assets/soapy-3-package-detail.png",    label:"Package + Tabby checkout" },
        { src:"assets/soapy-4-bookings.png",          label:"Current & past bookings" },
        { src:"assets/soapy-8-captain-dashboard.png", label:"Captain dashboard" },
        { src:"assets/soapy-6-captain-next.png",      label:"Captain — next job" },
        { src:"assets/soapy-7-history.png",           label:"Captain history" },
        { src:"assets/soapy-1-splash.png",            label:"Splash & branding" },
      ],
      glyph:'<path d="M12 3c3 4 5 7 5 10a5 5 0 01-10 0c0-3 2-6 5-10z" fill="white"/>' },
    { name:"Magnet", roles:"Customer & Merchant apps", pc1:"#332008", pc2:"#4a2f0c",
      stat:"Stores + custom orders",
      desc:"Shop companies or freelancers — size, color, and made-to-measure requests. Merchants accept or reject, handle returns, and move orders waiting → preparing → out for delivery. Scratch a card, reveal the code, type it in, and claim the win.",
      tags:["Scratch-to-win","Variants","Returns","Fulfillment"],
      links:[
        { group:"Customer", label:"App Store",   url:"https://apps.apple.com/us/app/magnet/id6746203011" },
        { group:"Customer", label:"Google Play", url:"https://play.google.com/store/apps/details?id=com.wady.magnet" },
        { group:"Merchant", label:"App Store",   url:"https://apps.apple.com/us/app/magnet-provider/id6746348471" },
        { group:"Merchant", label:"Google Play", url:"https://play.google.com/store/apps/details?id=com.wady.magnetprovider" },
      ],
      shots:[
        { src:"assets/magnet-2-stores.png",       label:"Store directory" },
        { src:"assets/magnet-3-store.png",        label:"Store profile" },
        { src:"assets/magnet-5-dashboard.png",    label:"Merchant dashboard" },
        { src:"assets/magnet-6-orders.png",       label:"Accept or reject" },
        { src:"assets/magnet-7-order-detail.png", label:"Fulfillment stepper" },
        { src:"assets/magnet-1-splash.png",       label:"Splash & branding" },
        { src:"assets/magnet-4-intro.png",        label:"App intro" },
      ],
      glyph:'<path d="M7 4v7a5 5 0 0010 0V4" stroke="white" stroke-width="1.6" fill="none" stroke-linecap="round"/><path d="M7 4h3M14 4h3" stroke="white" stroke-width="1.6" stroke-linecap="round"/>' },
    { name:"GlowUp", roles:"Customer & Provider apps", pc1:"#33101d", pc2:"#4a1a2b",
      stat:"Men’s & women’s salon + spa",
      desc:"Four verticals, timed services, then a barber or the cart. Pay wallet, Mada, or cash — shops accept or reject, add extras mid-job, and withdraw.",
      tags:["Timed booking","Wallet","Payouts","Accept / reject"],
      links:[
        { group:"Customer", label:"App Store",   url:"https://apps.apple.com/us/app/glow-up/id6615080351" },
        { group:"Customer", label:"Google Play", url:"https://play.google.com/store/apps/details?id=com.wady.naeima" },
        { group:"Provider", label:"App Store",   url:"https://apps.apple.com/us/app/glowup-provider/id6739752819" },
        { group:"Provider", label:"Google Play", url:"https://play.google.com/store/apps/details?id=com.wady.glowupprovider" },
      ],
      shots:[
        { src:"assets/glowup-1-home.png",     label:"Home & salon discovery" },
        { src:"assets/glowup-3-salon.png",    label:"Salon profile" },
        { src:"assets/glowup-4-services.png", label:"Hair care services" },
        { src:"assets/glowup-2-splash.png",   label:"Splash & branding" },
      ],
      glyph:'<path d="M12 2v6M12 16v6M4.9 4.9l4.2 4.2M14.9 14.9l4.2 4.2M2 12h6M16 12h6M4.9 19.1l4.2-4.2M14.9 9.1l4.2-4.2" stroke="white" stroke-width="1.5" stroke-linecap="round"/>' },
    { name:"WarshaStation", roles:"Customer & Vendor apps", pc1:"#181818", pc2:"#242424",
      stat:"Storefront + vendor ops",
      desc:"Each workshop is a store — services, parts, and rental. Book a slot or checkout. Vendors pass KYC, run branches and staff, redeem jobs by QR, and chat in-app on Pusher.",
      tags:["KYC","QR redeem","Pusher chat","Vendor ops"],
      links:[
        { label:"App Store",   url:"https://apps.apple.com/us/app/warshastation/id6744632393" },
        { label:"Google Play", url:"https://play.google.com/store/apps/details?id=com.warsha.warshastationnn" },
      ],
      shots:[
        { src:"assets/warsha-1-home.png",       label:"Home & services" },
        { src:"assets/warsha-2-listings.png",   label:"Workshop directory" },
        { src:"assets/warsha-3-workshop.png",   label:"Workshop profile" },
        { src:"assets/warsha-4-services.png",   label:"Services & pricing" },
        { src:"assets/warsha-5-chat.png",       label:"Chat with vendor" },
        { src:"assets/warsha-6-cars.png",       label:"Vehicle garage" },
        { src:"assets/warsha-7-onboarding.png", label:"User vs vendor" },
        { src:"assets/warsha-8-splash.png",     label:"Splash & branding" },
      ],
      glyph:'<rect x="4" y="10" width="16" height="6" rx="2" fill="white"/><circle cx="8" cy="18" r="1.6" fill="white"/><circle cx="16" cy="18" r="1.6" fill="white"/>' },
    { name:"Timey", roles:"Client project", pc1:"#16120e", pc2:"#2e241a",
      stat:"Social · creator booking · ads",
      desc:"A client's social platform — stories, real-time chat on Pusher, and an in-app camera, plus paid video sessions with creators and a self-serve ads flow. Split work across a 3-developer Flutter team and held final say on technical decisions, including client trade-offs such as AR-filter vendor options when the existing SDK became a cost issue.",
      tags:["Pusher chat","Agora","In-app camera","Ads"],
      live:false,
      shots:[
        { src:"assets/timey-1-stories.jpg",  label:"Stories feed" },
        { src:"assets/timey-2-chat.jpg",     label:"Real-time chat" },
        { src:"assets/timey-3-camera.jpg",   label:"In-app camera & filters" },
        { src:"assets/timey-4-profile.jpg",  label:"Creator profile & subscriptions" },
        { src:"assets/timey-5-trending.jpg", label:"Trending feed" },
        { src:"assets/timey-6-tips.jpg",     label:"Tips & supporters" },
        { src:"assets/timey-7-call.jpg",     label:"Creator video session" },
        { src:"assets/timey-8-splash.jpg",   label:"Splash & branding" },
      ],
      glyph:'<circle cx="12" cy="12" r="8" stroke="white" stroke-width="1.6" fill="none"/><circle cx="12" cy="12" r="2.4" fill="white"/>' },
    { name:"Nabtat Hasana", roles:"Produce e-commerce", pc1:"#181818", pc2:"#242424",
      stat:"Catalog store · OpenCart",
      desc:"Plants, vegetables, fruit, and dates — categories, subcategories, cart, coupons, gift vouchers, and a wishlist, wired to an OpenCart backend. RTL storefront in SAR.",
      tags:["OpenCart","Catalog","Coupons","RTL"],
      links:[
        { label:"App Store", url:"https://apps.apple.com/us/app/%D9%86%D8%A8%D8%AA%D8%A9-%D8%AD%D8%B3%D8%A7%D9%86%D8%A7/id6742134403" },
      ],
      shots:[
        { src:"assets/nabtat-1-splash.jpg",     label:"Splash & branding" },
        { src:"assets/nabtat-2-home.jpg",       label:"Home, banners & categories" },
        { src:"assets/nabtat-3-categories.jpg", label:"Category list" },
        { src:"assets/nabtat-4-listing.jpg",    label:"Most viewed products" },
        { src:"assets/nabtat-5-product.jpg",    label:"Product detail" },
        { src:"assets/nabtat-6-cart.jpg",       label:"Cart, coupon & totals" },
      ],
      glyph:'<path d="M12 21s-6-4.5-6-9a6 6 0 0112 0c0 4.5-6 9-6 9z" fill="white"/>' },
    { name:"Spicy Offers", roles:"Establishment companion", pc1:"#2a1a08", pc2:"#4a2c0c",
      stat:"QR redeem · usage analytics",
      desc:"Companion for venues on Spicy Offers. The shop shows a QR; subscribed customers scan it from the main app to take the discount. Venues then read weekly usage and sales from this app.",
      tags:["QR redeem","Usage analytics","OTP","RTL"],
      links:[
        { label:"Google Play", url:"https://play.google.com/store/apps/details?id=com.spicyoffers.facilitiesapp" },
      ],
      shots:[
        { src:"assets/spicy-1-splash.jpg",  label:"Splash & branding" },
        { src:"assets/spicy-2-otp.jpg",     label:"OTP login" },
        { src:"assets/spicy-3-qr.jpg",      label:"Establishment QR" },
        { src:"assets/spicy-4-reports.jpg", label:"Usage reports" },
        { src:"assets/spicy-5-account.jpg", label:"Account" },
      ],
      glyph:'<path d="M12 21s-7-5.2-7-10.2a7 7 0 0114 0c0 5-7 10.2-7 10.2z" fill="white"/><circle cx="12" cy="11" r="2.2" fill="#2a1a08"/>' },
  ];
